#!/usr/bin/env bash

# ==============================================================================
# SafeDep Vet Pipe: Report Maker
#
# Report in BitBucket are part of its Code Insights Feature
#
# Reports are basically:
#   TITLE, DESCRIPTION, LINKS, RESULT(PASS/FAIL), KEY-VALUE elements and ANNOTATIONS
#
# Docs: https://support.atlassian.com/bitbucket-cloud/docs/code-insights/
#
# Default file paths:
# code-insights-report.json contains metadata (title, desc, link, result and key-val elements etc)
# code-insights-annotations.json contains annotations (line by line markers)
#
#  FILENAMES ARE IN CONTRACT WITH gen-code-insights Go script
#
# These 2 files are generated by a helper Go application which takes `vet-report.json` as input (this is generated by pipe.sh, --report-json)
# ==============================================================================

# 0. Args
VET_JSON_REPORT_PATH="$1"

# Check if the vet json report is given
if [ -z "$VET_JSON_REPORT_PATH" ]; then
    echo "Error: No file path provided."
    echo "Usage: $0 path/to/vet-report.json"
    exit 1
fi

echo "Generating report from: $VET_JSON_REPORT_PATH"

# Call gen-code-insights CLI to generate code-insights-*.json files
/gen-code-insights --source-json-report-file "$VET_JSON_REPORT_PATH" --dest-report-file "code-insights-report.json" --dest-annotations-file "code-insights-annotations.json"
if [ $? -ne 0 ]; then
    echo "Error: Failed to generate code insights reports"
    exit 1
fi

# 1. Setup variables
REPO_PATH="${BITBUCKET_WORKSPACE}/${BITBUCKET_REPO_SLUG}"
COMMIT="${BITBUCKET_COMMIT}"
PROXY="http://localhost:29418"
REPORT_ID="dependency-scan-$(date +%s)" # Unique Report ID

echo "Starting report upload for commit: $COMMIT"

# 2. Create the Base Report
curl -s --proxy $PROXY -X PUT \
  "http://api.bitbucket.org/2.0/repositories/${REPO_PATH}/commit/${COMMIT}/reports/${REPORT_ID}" \
  -H "Content-Type: application/json" \
  -d @code-insights-report.json

# 4. POST the array to the annotations endpoint
# Note: There is NO annotation ID in this URL because it is a bulk POST
curl -s --proxy $PROXY -X POST \
  "http://api.bitbucket.org/2.0/repositories/${REPO_PATH}/commit/${COMMIT}/reports/${REPORT_ID}/annotations" \
  -H "Content-Type: application/json" \
  -d @code-insights-annotations.json

echo "Bulk annotations successfully posted to report: $REPORT_ID"
