#!/usr/bin/env bash

# ==============================================================================
# SafeDep Vet Pipe: Report Maker
#
# Report in BitBucket are part of its Code Insights Feature
#
# Reports are basically:
#   TITLE, DESCRIPTION, LINKS, RESULT(PASS/FAIL), KEY-VALUE elements and ANNOTATIONS
#
# Docs: https://support.atlassian.com/bitbucket-cloud/docs/code-insights/
#
# The artifact files are generated by a vet Bitbucket reports
# ==============================================================================

echo ""
echo "[~] Running Scan Report and Annotation Update Script"
echo ""

# Args
BB_META_REPORT_PATH="$1"
BB_ANNOTATIONS_REPORT_PATH="$2"

if [ -z "$BB_META_REPORT_PATH" ]; then
    echo "Error: Missing Bitbucket Meta Report path."
    echo "Usage: $0 path/to/code-insights-meta-report.json"
    exit 1
fi

if [ -z "$BB_ANNOTATIONS_REPORT_PATH" ]; then
    echo "Error: Missing Bitbucket Annotations Report path."
    echo "Usage: $0 path/to/code-insights-annotations-report.json"
    exit 1
fi

echo "Publishing BitBucket Code Insights Reports"


# Setup variables
REPO_PATH="${BITBUCKET_WORKSPACE}/${BITBUCKET_REPO_SLUG}"
COMMIT="${BITBUCKET_COMMIT}"
REPORT_ID="safedep-vet-scan"

# Bitbucket API Proxy for Auth-less API access
HOST_GATEWAY="172.17.0.1"
PROXY_PORT="29418"
INTERNAL_PROXY="http://${HOST_GATEWAY}:${PROXY_PORT}"

export HTTP_PROXY="$INTERNAL_PROXY"
export HTTPS_PROXY="$INTERNAL_PROXY"
# Optional: Ensure we don't try to proxy internal traffic
export NO_PROXY="localhost,127.0.0.1"

echo "Starting report upload for commit: $COMMIT"

# Create the Base Report
curl -X PUT \
  "https://api.bitbucket.org/2.0/repositories/${REPO_PATH}/commit/${COMMIT}/reports/${REPORT_ID}" \
  -H "Content-Type: application/json" \
  -d "@$BB_META_REPORT_PATH"

# POST the array to the annotations endpoint
# Note: There is NO annotation ID in this URL because it is a bulk POST
curl -X POST \
  "https://api.bitbucket.org/2.0/repositories/${REPO_PATH}/commit/${COMMIT}/reports/${REPORT_ID}/annotations" \
  -H "Content-Type: application/json" \
  -d "@$BB_ANNOTATIONS_REPORT_PATH"

echo "Bulk annotations successfully posted to report: $REPORT_ID"
