#!/usr/bin/env bash

# ==============================================================================
# SafeDep Vet Pipe: Report Maker
#
# Report in BitBucket are part of its Code Insights Feature
#
# Reports are basically:
#   TITLE, DESCRIPTION, LINKS, RESULT(PASS/FAIL), KEY-VALUE elements and ANNOTATIONS
#
# Docs: https://support.atlassian.com/bitbucket-cloud/docs/code-insights/
#
# The artifact files are generated by a vet Bitbucket reports
# ==============================================================================

echo ""
echo "[~] Running Scan Report and Annotation Update Script"
echo ""

# Args
BB_META_REPORT_PATH="$1"
BB_ANNOTATIONS_REPORT_PATH="$2"

if [ -z "$BB_META_REPORT_PATH" ]; then
    echo "Error: Missing Bitbucket Meta Report path."
    echo "Usage: $0 code-insights-meta-report.json code-insights-annotations-report.json"
    exit 1
fi

if [ -z "$BB_ANNOTATIONS_REPORT_PATH" ]; then
    echo "Error: Missing Bitbucket Annotations Report path."
    echo "Usage: $0 code-insights-meta-report.json code-insights-annotations-report.json"
    exit 1
fi

echo "Publishing BitBucket Code Insights Reports"

# Setup variables
REPO_PATH="${BITBUCKET_WORKSPACE}/${BITBUCKET_REPO_SLUG}"
COMMIT="${BITBUCKET_COMMIT}"
REPORT_ID="safedep-vet-scan"

# Bitbucket Supports proxy at localhost:29418 for accessing its API
# without authentication, since we are in 3rd party container, we have use
# docker host network to access it
PROXY="http://host.docker.internal:29418"

echo "Starting report upload for commit: $COMMIT"

# Create the Base Report
curl -s --proxy "$PROXY" -X PUT \
  "http://api.bitbucket.org/2.0/repositories/${REPO_PATH}/commit/${COMMIT}/reports/${REPORT_ID}" \
  -H "Content-Type: application/json" \
  -d "@$BB_META_REPORT_PATH"

# POST the array to the annotations endpoint
# Note: There is NO annotation ID in this URL because it is a bulk POST
curl -s --proxy "$PROXY" -X POST \
  "http://api.bitbucket.org/2.0/repositories/${REPO_PATH}/commit/${COMMIT}/reports/${REPORT_ID}/annotations" \
  -H "Content-Type: application/json" \
  -d "@$BB_ANNOTATIONS_REPORT_PATH"

echo ""

echo "Bulk annotations successfully posted to report: $REPORT_ID"
